Create Database QLBH
Use QLBH
--TUAN 1
--Cau 1:
CREATE TABLE KHACHHANG(
	MAKH CHAR(4) NOT NULL,
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	DOANHSO MONEY,
	NGDK SMALLDATETIME
	CONSTRAINT KH_MAKH_PK primary key (MAKH)
)
GO
CREATE TABLE NHANVIEN(
	MANV CHAR(4) NOT NULL,
	HOTEN VARCHAR(40),
	SODT VARCHAR(20),
	NGVL SMALLDATETIME
	CONSTRAINT NV_MANV_PK PRIMARY KEY (MANV)
)
GO 
CREATE TABLE SANPHAM(
	MASP CHAR(4) NOT NULL,
	TENSP VARCHAR(40),
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA MONEY
	CONSTRAINT SP_MASP_PK PRIMARY KEY(MASP)
)
GO 
CREATE TABLE HOADON(
	SOHD INT NOT NULL,
	NGHD SMALLDATETIME,
	MAKH CHAR(4),
	MANV CHAR(4),
	TRIGIA MONEY
	CONSTRAINT HD_SOHD_PK PRIMARY KEY(SOHD)
)
GO
CREATE TABLE CTHD(
	SOHD INT NOT NULL,
	MASP CHAR(4) NOT NULL,
	SL INT
	CONSTRAINT CTHD_PK PRIMARY KEY(SOHD, MASP)
)

ALTER TABLE HOADON ADD CONSTRAINT HD_MAKH_FK FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH),
CONSTRAINT HD_MANV_FK FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)
GO
ALTER TABLE CTHD ADD CONSTRAINT CTHD_MASP_FK FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP)
GO 
ALTER TABLE CTHD ADD CONSTRAINT CTHD_SOHD_FK FOREIGN KEY (SOHD) REFERENCES HOADON (SOHD)

--Cau 2:
ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20)

--Cau 3:
ALTER TABLE KHACHHANG ADD LOAIKH TINYINT

--Cau 4:
ALTER TABLE SANPHAM ALTER COLUMN GHICHU VARCHAR(100)

--Cau 5:
ALTER TABLE SANPHAM DROP COLUMN GHICHU 

--Cau 6:
ALTER TABLE KHACHHANG ALTER COLUMN LOAIKH VARCHAR(20)
ALTER TABLE KHACHHANG ADD CHECK(LOAIKH IN ('vanglai', 'thuong xuyen', 'vip'))

--Cau 7:
ALTER TABLE SANPHAM ADD CONSTRAINT DON_VI_TINH CHECK (DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'))

--Cau 8:
ALTER TABLE SANPHAM ADD CONSTRAINT DON_GIA CHECK (GIA >= 500)

--Cau 10:
ALTER TABLE KHACHHANG ADD CONSTRAINT NGAYDK CHECK (NGDK > NGSINH)

--TUAN 2
--Phan II:
--Cau 1: 


SELECT * FROM KHACHHANG;
SELECT * FROM NHANVIEN;
SELECT * FROM SANPHAM;
SELECT * FROM HOADON;
SELECT * FROM CTHD;


--Cau 2:
SELECT * INTO SANPHAM1 FROM SANPHAM
SELECT * INTO KHACHHANG1 FROM KHACHHANG
select * from SANPHAM1

--Cau 3
UPDATE SANPHAM1
SET GIA = GIA * 1.05
WHERE NUOCSX = 'THAILAN'

--Cau 4:
UPDATE SANPHAM1
SET GIA = GIA * 0.95
WHERE (NUOCSX = 'TRUNGQUOC') AND (GIA <= 10000)

--Cau 5:
UPDATE KHACHHANG1
SET LOAIKH = 'Vip'
WHERE (
	((NGDK < '1/1/2007') AND (DOANHSO >= 10000000)) OR		
	((NGDK >= '1/1/2007') AND (DOANHSO > 2000000))
)

--Phan III:
--Cau 1:
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'TRUNGQUOC';

--Cau 2:
SELECT MASP, TENSP
FROM SANPHAM
WHERE DVT = 'cay' or DVT = 'quyen';

--Cau 3:
SELECT MASP, TENSP
FROM SANPHAM
WHERE MASP LIKE 'B%01';

--Cau 4:
SELECT MASP, TENSP
FROM SANPHAM
WHERE (NUOCSX = 'TRUNGQUOC') AND (GIA BETWEEN 30000 AND 40000);

--Cau 5:
SELECT MASP, TENSP
FROM SANPHAM
WHERE (NUOCSX = 'TRUNGQUOC' OR NUOCSX = 'THAILAN') AND (GIA BETWEEN 30000 AND 40000);

--Cau 6:
SELECT SOHD, TRIGIA
FROM HOADON
WHERE NGHD = '1/1/2007' OR NGHD = '2/1/2007'

--Cau 7:
SELECT SOHD, TRIGIA
FROM HOADON
WHERE MONTH(NGHD) = 1 AND YEAR(NGHD) = 2007
ORDER BY NGHD ASC, TRIGIA DESC;

--Cau 8:
SELECT MAKH, HOTEN
FROM KHACHHANG AS KH
WHERE 

--Cau 9:


--Cau 10:


--Cau 11:


--Cau 12: